baseURL = "https://davidreynolds.xyz"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "David Reynolds"
theme = "blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "David Reynolds"
  authorThumb = "images/author.png"
  
  youtubeChannelId = "UCqnoRx37mPhrAjXMxSDOA6w"
  githubUsername = "David-Rey"
  linkedinUsername = "david-reynolds-2b47471b9"
  
  blogTitle = "Articles"
  blogSubTitle = "View the latest Posts"
  trendingBlogIcon = "images/blog/icon.svg"

  fabformURL  = "xnnabbrp"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
